export const ADD_USER_TOKEN = "ADD_USER_TOKEN";
export const SEND_LOGIN_DATA = "SEND_LOGIN_DATA";
export const ADD_USER_DATA = "ADD_USER_DATA";

export const REQUEST_STARTED = "REQUEST_STARTED";
export const REQUEST_FINISHED = "REQUEST_FINISHED";

export const TRY_AUTH = "TRY_AUTH";

// Users.js
export const DOWNLOAD_USER_SUCCESS = "DOWNLOAD_USER_SUCCESS";
export const DOWNLOAD_ALL_USERS_SUCCESS = "DOWNLOAD_ALL_USERS_SUCCESS";
export const REMOVE_USER_DATA_FROM_STORE = "REMOVE_USER_DATA_FROM_STORE";

// Orders.js
export const SAVE_ORDER = "SAVE_ORDER";
export const SET_FILTER_FLAG = "SET_FILTER_FLAG";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DOWNLOAD_ALL_ORDERS_SUCCESS = "DOWNLOAD_ALL_ORDERS_SUCCESS";
export const DOWNLOAD_MY_ORDERS_SUCCESS = "DOWNLOAD_MY_ORDERS_SUCCESS";

//Chat.js
export const SAVE_CHAT = "SAVE_CHAT";
